from typing import Protocol

from dto import file_dto


class FileServiceProtocol(Protocol):
    async def initiate_upload(
        self, data: file_dto.InitiateUploadDTO
    ) -> file_dto.InitiatedUploadDTO: ...

    async def complete_upload(self, data: file_dto.CompleteUploadDTO) -> None: ...

    async def abort_upload(self, data: file_dto.AbortUploadDTO) -> None: ...

    async def file_info(self, data: file_dto.FileDTO) -> file_dto.FileInfoDTO: ...

    async def file_list(self, user_id: str) -> list[file_dto.FileInfoDTO]: ...

    async def download(self, data: file_dto.FileDTO) -> str: ...

    async def delete(self, data: file_dto.DeleteDTO) -> None: ...

    async def delete_all(self, user_id: str) -> None: ...
