{{- if .Values.monitoring.enabled }}
{{- $prometheusName := include "cloud-storage.prometheus.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $prometheusName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
    {{- include "cloud-storage.labels" . | nindent 4 }}
spec:
  selector:
    app: prometheus
  ports:
  - name: http
    port: 9090
    targetPort: http
  type: ClusterIP
{{- end }}
