services:
  gateway:
    image: ghcr.io/j3rrryy/cloud_storage:gateway-latest
    env_file:
      - ./test/.env
    command: bash -c "
      uv sync --group test &&
      uv run --group test pytest ./tests --cov=. --cov-config=./tests/.coveragerc --cov-report=xml"
    container_name: gateway_test

  auth:
    image: ghcr.io/j3rrryy/cloud_storage:auth-latest
    env_file:
      - ./test/.env
    command: bash -c "
      uv sync --group test &&
      uv run --group test pytest ./tests --cov=. --cov-config=./tests/.coveragerc --cov-report=xml"
    container_name: auth_test

  file:
    image: ghcr.io/j3rrryy/cloud_storage:file-latest
    env_file:
      - ./test/.env
    command: bash -c "
      uv sync --group test &&
      uv run --group test pytest ./tests --cov=. --cov-config=./tests/.coveragerc --cov-report=xml"
    container_name: file_test

  mail:
    image: ghcr.io/j3rrryy/cloud_storage:mail-latest
    env_file:
      - ./test/.env
    command: bash -c "
      uv sync --group test &&
      uv run --group test pytest ./tests --cov=. --cov-config=./tests/.coveragerc --cov-report=xml"
    container_name: mail_test
