apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloud-storage.file.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: file
    {{- include "cloud-storage.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.file.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  POSTGRES_HOST: {{ .Release.Name }}-file-postgres
  POSTGRES_PORT: "5432"
  REDIS_HOST: {{ .Release.Name }}-file-redis
  REDIS_PORT: "6379"
  MINIO_HOST: {{ include "cloud-storage.minio.fullname" . }}
  MINIO_PORT: {{ .Values.minio.service.port | quote }}
