apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-storage.file.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: file
    {{- include "cloud-storage.labels" . | nindent 4 }}
spec:
  selector:
    app: file
  ports:
  - name: grpc
    port: {{ .Values.file.service.grpcPort }}
    targetPort: grpc
  - name: http
    port: {{ .Values.file.service.httpPort }}
    targetPort: http
  type: ClusterIP
