global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "gateway"
    metrics_path: "/api/metrics"
    static_configs:
      - targets: ["gateway:8000"]

  - job_name: "auth"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["auth:8000"]

  - job_name: "file"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["file:8000"]

  - job_name: "minio"
    metrics_path: "/minio/v2/metrics/cluster"
    static_configs:
      - targets: ["minio:9000"]

  - job_name: "mail"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["mail:8000"]

  - job_name: "loki"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["loki:3100"]

  - job_name: "promtail"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["promtail:9080"]
