{{- if .Values.secrets.mail }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloud-storage.mail.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: mail
    {{- include "cloud-storage.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets.mail }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
