environment: dev

gateway:
  env:
    APP_NAME: Cloud Storage
    VERSION: "1.5.3"
    DEBUG: "1"
    ALLOWED_ORIGINS: http://localhost:3000

auth:
  env:
    APP_NAME: Cloud Storage
    VERSION: "1.5.3"
    DEBUG: "1"
    POSTGRES_DB: cloud_storage
    POSTGRES_USER: <username>
    REDIS_DB: "0"
    REDIS_USER: default

authPostgres:
  auth:
    username: <username>
    password: "<password>"
    database: cloud_storage

authRedis:
  auth:
    password: "<password>"

file:
  env:
    POSTGRES_DB: cloud_storage
    POSTGRES_USER: <username>
    REDIS_DB: "0"
    REDIS_USER: default
    MINIO_S3_BUCKET: s3-files
    MAX_FILE_SIZE: "16106127360"
    UPLOAD_CHUNK_SIZE: "73400320"

filePostgres:
  auth:
    username: <username>
    password: "<password>"
    database: cloud_storage

fileRedis:
  auth:
    password: "<password>"

mail:
  env:
    APP_NAME: Cloud Storage
    EMAIL_CONFIRMATION_URL: http://localhost/api/v1/auth/confirm-email?token=

minio:
  auth:
    rootUser: <username>
    rootPassword: "<password>"

secrets:
  auth:
    SECRET_KEY: "<Base64-encoded PEM EdDSA key>"
  mail:
    MAIL_USERNAME: "<username>"
    MAIL_PASSWORD: "<password>"
    MAIL_HOSTNAME: "<hostname>"
    MAIL_PORT: "<port>"
  grafana:
    GF_SECURITY_ADMIN_USER: <username>
    GF_SECURITY_ADMIN_PASSWORD: "<password>"
