{{- if (index .Values "auth-postgres").userDatabase.password.value }}
apiVersion: v1
kind: Secret
metadata:
  name: auth-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: auth-postgres
    {{- include "cloud-storage.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ (index .Values "auth-postgres").userDatabase.password.value | b64enc | quote }}
{{- end }}

---

{{- if (index .Values "auth-redis").redisConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: auth-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: auth-redis
    {{- include "cloud-storage.labels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ (index .Values "auth-redis").redisConfig | regexFind "requirepass ([^\n]+)" | regexReplaceAll "requirepass " "" | b64enc | quote }}
{{- end }}

---

{{- if (index .Values "file-postgres").userDatabase.password.value }}
apiVersion: v1
kind: Secret
metadata:
  name: file-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: file-postgres
    {{- include "cloud-storage.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ (index .Values "file-postgres").userDatabase.password.value | b64enc | quote }}
{{- end }}

---

{{- if (index .Values "file-redis").redisConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: file-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: file-redis
    {{- include "cloud-storage.labels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ (index .Values "file-redis").redisConfig | regexFind "requirepass ([^\n]+)" | regexReplaceAll "requirepass " "" | b64enc | quote }}
{{- end }}

---

{{- if .Values.minio.auth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-minio
  namespace: {{ .Release.Namespace }}
  labels:
    app: minio
    {{- include "cloud-storage.labels" . | nindent 4 }}
type: Opaque
data:
  root-user: {{ .Values.minio.auth.rootUser | b64enc | quote }}
  root-password: {{ .Values.minio.auth.rootPassword | b64enc | quote }}
{{- end }}
