{{- if (index .Values "auth-postgres").userDatabase.password.value }}
apiVersion: v1
kind: Secret
metadata:
  name: auth-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: auth-postgres
    {{- include "cloud-storage.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ (index .Values "auth-postgres").userDatabase.password.value | b64enc | quote }}
{{- end }}

---

{{- if (index .Values "auth-redis").redisConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: auth-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: auth-redis
    {{- include "cloud-storage.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ (index .Values "auth-redis").auth.password | b64enc | quote }}
{{- end }}

---

{{- if (index .Values "file-postgres").userDatabase.password.value }}
apiVersion: v1
kind: Secret
metadata:
  name: file-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: file-postgres
    {{- include "cloud-storage.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ (index .Values "file-postgres").userDatabase.password.value | b64enc | quote }}
{{- end }}

---

{{- if (index .Values "file-redis").redisConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: file-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: file-redis
    {{- include "cloud-storage.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ (index .Values "file-redis").auth.password | b64enc | quote }}
{{- end }}

---

{{- if and .Values.minio.rootUser .Values.minio.rootPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-minio
  namespace: {{ .Release.Namespace }}
  labels:
    app: minio
    {{- include "cloud-storage.labels" . | nindent 4 }}
type: Opaque
data:
  rootUser: {{ .Values.minio.rootUser | b64enc | quote }}
  rootPassword: {{ .Values.minio.rootPassword | b64enc | quote }}
{{- end }}
