from typing import Protocol, runtime_checkable

from dto import auth_dto, file_dto


@runtime_checkable
class ApplicationFacadeProtocol(Protocol):
    async def register(self, data: auth_dto.RegistrationDTO) -> None: ...

    async def verify_email(self, verification_token: str) -> None: ...

    async def request_reset_code(self, email: str) -> str: ...

    async def validate_reset_code(self, data: auth_dto.ResetCodeDTO) -> bool: ...

    async def reset_password(self, data: auth_dto.ResetPasswordDTO) -> None: ...

    async def log_in(self, data: auth_dto.LogInDTO) -> auth_dto.LogInDataDTO: ...

    async def log_out(self, access_token: str) -> None: ...

    async def resend_verification_mail(self, access_token: str) -> None: ...

    async def auth(self, access_token: str) -> str: ...

    async def refresh(self, data: auth_dto.RefreshDTO) -> auth_dto.TokensDTO: ...

    async def session_list(self, access_token: str) -> list[auth_dto.SessionDTO]: ...

    async def revoke_session(self, data: auth_dto.RevokeSessionDTO) -> None: ...

    async def profile(self, access_token: str) -> auth_dto.ProfileDTO: ...

    async def update_email(self, data: auth_dto.UpdateEmailDTO) -> None: ...

    async def update_password(self, data: auth_dto.UpdatePasswordDTO) -> None: ...

    async def delete_profile(self, access_token: str) -> None: ...

    async def initiate_upload(
        self, access_token: str, data: file_dto.InitiateUploadDTO
    ) -> file_dto.InitiatedUploadDTO: ...

    async def complete_upload(
        self, access_token: str, data: file_dto.CompleteUploadDTO
    ) -> None: ...

    async def abort_upload(
        self, access_token: str, data: file_dto.AbortUploadDTO
    ) -> None: ...

    async def file_info(
        self, access_token: str, data: file_dto.FileDTO
    ) -> file_dto.FileInfoDTO: ...

    async def file_list(self, access_token: str) -> list[file_dto.FileInfoDTO]: ...

    async def download(self, access_token: str, data: file_dto.FileDTO) -> str: ...

    async def delete(self, access_token: str, data: file_dto.DeleteDTO) -> None: ...

    async def delete_all(self, access_token: str) -> None: ...
