from typing import Protocol

from dto import auth_dto, mail_dto


class AuthServiceProtocol(Protocol):
    async def register(
        self, data: auth_dto.RegistrationDTO
    ) -> mail_dto.VerificationMailDTO: ...

    async def verify_email(self, verification_token: str) -> None: ...

    async def request_reset_code(self, email: str) -> auth_dto.ResetInfoDTO: ...

    async def validate_reset_code(self, data: auth_dto.ResetCodeDTO) -> bool: ...

    async def reset_password(self, data: auth_dto.ResetPasswordDTO) -> None: ...

    async def log_in(self, data: auth_dto.LogInDTO) -> auth_dto.LogInDataDTO: ...

    async def log_out(self, access_token: str) -> None: ...

    async def resend_verification_mail(
        self, access_token: str
    ) -> mail_dto.VerificationMailDTO: ...

    async def auth(self, access_token: str) -> str: ...

    async def refresh(self, data: auth_dto.RefreshDTO) -> auth_dto.TokensDTO: ...

    async def session_list(self, access_token: str) -> list[auth_dto.SessionDTO]: ...

    async def revoke_session(self, data: auth_dto.RevokeSessionDTO) -> None: ...

    async def profile(self, access_token: str) -> auth_dto.ProfileDTO: ...

    async def update_email(
        self, data: auth_dto.UpdateEmailDTO
    ) -> mail_dto.VerificationMailDTO: ...

    async def update_password(self, data: auth_dto.UpdatePasswordDTO) -> None: ...

    async def delete_profile(self, access_token: str) -> str: ...
