# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import warnings

import grpc
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

from . import file_pb2 as file__pb2

GRPC_GENERATED_VERSION = "1.74.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in file_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class FileStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadFile = channel.unary_unary(
            "/file.File/UploadFile",
            request_serializer=file__pb2.UploadFileRequest.SerializeToString,
            response_deserializer=file__pb2.FileURLResponse.FromString,
            _registered_method=True,
        )
        self.FileInfo = channel.unary_unary(
            "/file.File/FileInfo",
            request_serializer=file__pb2.FileOperationRequest.SerializeToString,
            response_deserializer=file__pb2.FileInfoResponse.FromString,
            _registered_method=True,
        )
        self.FileList = channel.unary_unary(
            "/file.File/FileList",
            request_serializer=file__pb2.UserId.SerializeToString,
            response_deserializer=file__pb2.FileListResponse.FromString,
            _registered_method=True,
        )
        self.DownloadFile = channel.unary_unary(
            "/file.File/DownloadFile",
            request_serializer=file__pb2.FileOperationRequest.SerializeToString,
            response_deserializer=file__pb2.FileURLResponse.FromString,
            _registered_method=True,
        )
        self.DeleteFiles = channel.unary_unary(
            "/file.File/DeleteFiles",
            request_serializer=file__pb2.DeleteFilesRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            _registered_method=True,
        )
        self.DeleteAllFiles = channel.unary_unary(
            "/file.File/DeleteAllFiles",
            request_serializer=file__pb2.UserId.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            _registered_method=True,
        )


class FileServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def FileInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def FileList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DownloadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteAllFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_FileServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "UploadFile": grpc.unary_unary_rpc_method_handler(
            servicer.UploadFile,
            request_deserializer=file__pb2.UploadFileRequest.FromString,
            response_serializer=file__pb2.FileURLResponse.SerializeToString,
        ),
        "FileInfo": grpc.unary_unary_rpc_method_handler(
            servicer.FileInfo,
            request_deserializer=file__pb2.FileOperationRequest.FromString,
            response_serializer=file__pb2.FileInfoResponse.SerializeToString,
        ),
        "FileList": grpc.unary_unary_rpc_method_handler(
            servicer.FileList,
            request_deserializer=file__pb2.UserId.FromString,
            response_serializer=file__pb2.FileListResponse.SerializeToString,
        ),
        "DownloadFile": grpc.unary_unary_rpc_method_handler(
            servicer.DownloadFile,
            request_deserializer=file__pb2.FileOperationRequest.FromString,
            response_serializer=file__pb2.FileURLResponse.SerializeToString,
        ),
        "DeleteFiles": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteFiles,
            request_deserializer=file__pb2.DeleteFilesRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "DeleteAllFiles": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteAllFiles,
            request_deserializer=file__pb2.UserId.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "file.File", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("file.File", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class File(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadFile(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/file.File/UploadFile",
            file__pb2.UploadFileRequest.SerializeToString,
            file__pb2.FileURLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def FileInfo(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/file.File/FileInfo",
            file__pb2.FileOperationRequest.SerializeToString,
            file__pb2.FileInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def FileList(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/file.File/FileList",
            file__pb2.UserId.SerializeToString,
            file__pb2.FileListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DownloadFile(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/file.File/DownloadFile",
            file__pb2.FileOperationRequest.SerializeToString,
            file__pb2.FileURLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteFiles(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/file.File/DeleteFiles",
            file__pb2.DeleteFilesRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteAllFiles(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/file.File/DeleteAllFiles",
            file__pb2.UserId.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
