name: Rollback

on:
  workflow_dispatch:

permissions:
  packages: write

jobs:
  rollback:
    if: ${{ vars.DEPLOY == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [gateway, auth, file, mail]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}

      - name: Get previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1.4.0

      - name: Tag the previous Docker image as the latest
        run: |
          PREVIOUS_TAG=${{ steps.previoustag.outputs.tag }}
          PREVIOUS_TAG_WITHOUT_V=${PREVIOUS_TAG#v}

          docker pull ghcr.io/${{ github.repository }}:${{ matrix.service }}-$PREVIOUS_TAG_WITHOUT_V
          docker tag \
            ghcr.io/${{ github.repository }}:${{ matrix.service }}-$PREVIOUS_TAG_WITHOUT_V \
            ghcr.io/${{ github.repository }}:${{ matrix.service }}-latest
          docker push ghcr.io/${{ github.repository }}:${{ matrix.service }}-latest

  rollback-deploy:
    if: ${{ vars.DEPLOY == 'true' }}
    runs-on: ubuntu-latest
    needs: rollback
    steps:
      - name: Rollback the app
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: |
            echo "${{ secrets.PASSWORD }}" | sudo -S sh -c "
            cd cloud_storage &&
            docker compose -f docker-compose.prod.yml up gateway auth file mail --force-recreate -d &&
            docker image prune -f
            "
